inbounds:
- listen: 0.0.0.0:9000
  transport: grpc
  mtls:
    certFile: "/usr/local/etc/yeager/server-cert.pem"
    keyFile: "/usr/local/etc/yeager/server-key.pem"
    caFile: "/usr/local/etc/yeager/ca-cert.pem"
rules:
- ip-cidr,127.0.0.1/8,reject
- ip-cidr,192.168.0.0/16,reject
- domain,localhost,reject
- final,direct
