verbose: true
socksListen: 127.0.0.1:1081
httpListen: 127.0.0.1:8081
tunnelClients:
    - policy: proxy
      address: 127.0.0.1:10812
      type: grpc
      certPEM: |
          -----BEGIN CERTIFICATE-----
          MIIBpjCCAUugAwIBAgIQceNWBH9gLKrWUNhgDuNYMDAKBggqhkjOPQQDAjAkMRAw
          DgYDVQQKEwdBY21lIENvMRAwDgYDVQQDEwdSb290IENBMB4XDTIyMTExNzEzMzIx
          N1oXDTIzMTExNzEzMzIxN1owEjEQMA4GA1UEChMHQWNtZSBDbzBZMBMGByqGSM49
          AgEGCCqGSM49AwEHA0IABKbtGakfrYr/aR0oXLU3AP9NQ71jsfNwk9MEMG58q+Zo
          mNaF6TeyevUqDDebpODYdkLx7HnwlhWN68PVGECyFD6jcTBvMA4GA1UdDwEB/wQE
          AwIHgDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIw
          ADAfBgNVHSMEGDAWgBSV7lqagZ4wzreOYurP6iX1pvpuTTAPBgNVHREECDAGhwR/
          AAABMAoGCCqGSM49BAMCA0kAMEYCIQDOJ27haosE2Lqnhy8Z0R58fVsNEos8ZmHa
          UT4/ShOdQwIhAMxYQ4PasORQ9P48Utf6nNtsj0H7+IB2BAlOrCUyrUay
          -----END CERTIFICATE-----
      keyPEM: |
          -----BEGIN EC PRIVATE KEY-----
          MHcCAQEEIK8SC6LlmO45FSlYG4OUNIfXLlhoM1Dr8nEy+ZFfcM56oAoGCCqGSM49
          AwEHoUQDQgAEpu0ZqR+tiv9pHShctTcA/01DvWOx83CT0wQwbnyr5miY1oXpN7J6
          9SoMN5uk4Nh2QvHsefCWFY3rw9UYQLIUPg==
          -----END EC PRIVATE KEY-----
      caPEM: |
          -----BEGIN CERTIFICATE-----
          MIIBqDCCAU6gAwIBAgIRAPuKOVYvc5ebOwyBwSTghdowCgYIKoZIzj0EAwIwJDEQ
          MA4GA1UEChMHQWNtZSBDbzEQMA4GA1UEAxMHUm9vdCBDQTAeFw0yMjExMTcxMzMy
          MTdaFw0yMzExMTcxMzMyMTdaMCQxEDAOBgNVBAoTB0FjbWUgQ28xEDAOBgNVBAMT
          B1Jvb3QgQ0EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAR7JmBJMt9Q1652d4WZ
          jpmd2+nmghwCoqjbonf7on6/KZRQRR3ApNxGgtPEustVPcqTcQvWe17R28PLja1F
          q+o+o2EwXzAOBgNVHQ8BAf8EBAMCAgQwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsG
          AQUFBwMCMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFJXuWpqBnjDOt45i6s/q
          JfWm+m5NMAoGCCqGSM49BAMCA0gAMEUCIBAFPb6HIxKIot0EdXspPyL9U5qsqhnh
          TYnSfDnSJ94AAiEA0oLoQ3wDyGEnriSad0HoJ1AvfRFGDV6sQdrIaly0Jv0=
          -----END CERTIFICATE-----
rules:
  - final,proxy
