name: Publish Container image
on:
  release:
    types: [published]
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: extract-version
        run: |
          printf "::set-output name=%s::%s\n" version "${GITHUB_REF#refs/tags/}"

      - name: Push image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            en180706/yeager:latest
            en180706/yeager:${{ steps.extract-version.outputs.version }}
      - name: Push image to github
        uses: docker/build-push-action@v2
        with:
          push: true
          # github.repository as <account>/<repo>
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.extract-version.outputs.version }}
