name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Go build
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o release/yeager .
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag yeager:$(date +%s)
