name: Release

on:
  release:
    types: [published]

jobs:
  build_binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.3

      - name: Build
        run: |
          cp route/testdata/geosite.dat .
          ldflags="-X main.version=${GITHUB_REF#refs/tags/}"

          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="${ldflags}" -o yeager .
          tar -czf yeager-linux-amd64.tar.gz yeager geosite.dat README.md
          shasum -a 256 yeager-linux-amd64.tar.gz >> shasums.txt

          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags="${ldflags}" -o yeager .
          tar -czf yeager-linux-arm64.tar.gz yeager geosite.dat README.md
          shasum -a 256 yeager-linux-arm64.tar.gz >> shasums.txt

          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="${ldflags}" -o yeager .
          tar -czf yeager-macos-amd64.tar.gz yeager geosite.dat README.md
          shasum -a 256 yeager-macos-amd64.tar.gz >> shasums.txt

          CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build -ldflags="${ldflags}" -o yeager .
          tar -czf yeager-freebsd-amd64.tar.gz yeager geosite.dat README.md
          shasum -a 256 yeager-freebsd-amd64.tar.gz >> shasums.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            yeager-linux-amd64.tar.gz
            yeager-linux-arm64.tar.gz
            yeager-macos-amd64.tar.gz
            yeager-freebsd-amd64.tar.gz
            shasums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: extract-version
        run: |
          printf "::set-output name=%s::%s\n" tag-name "${GITHUB_REF#refs/tags/}"

      - name: Update homebrew formula
        uses: mislav/bump-homebrew-formula-action@v1.12
        with:
          formula-name: yeager
          formula-path: Formula/yeager.rb
          homebrew-tap: chenen3/homebrew-yeager
          base-branch: master
          download-url: https://github.com/chenen3/yeager/releases/download/${{ steps.extract-version.outputs.tag-name }}/yeager-macos-amd64.tar.gz
          commit-message: |
            {{formulaName}} {{version}}

            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}

  build_container:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: extract-version
        run: |
          printf "::set-output name=%s::%s\n" version "${GITHUB_REF#refs/tags/}"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.extract-version.outputs.version }}
