name: Release asset

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.1

      - name: Test
        run: go test -v ./...

      - name: Build
        run: |
          wget https://github.com/v2fly/domain-list-community/raw/release/dlc.dat -O geosite.dat
          ldflags="-X main.Version=${GITHUB_REF#refs/tags/}"

          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="${ldflags}" -o yeager .
          tar -czf yeager-linux-amd64.tar.gz yeager geosite.dat README.md
          shasum -a 256 yeager-linux-amd64.tar.gz >> shasums

          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="${ldflags}" -o yeager .
          tar -czf yeager-macos-amd64.tar.gz yeager geosite.dat README.md
          shasum -a 256 yeager-macos-amd64.tar.gz >> shasums

          CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build -ldflags="${ldflags}" -o yeager .
          tar -czf yeager-freebsd-amd64.tar.gz yeager geosite.dat README.md
          shasum -a 256 yeager-freebsd-amd64.tar.gz >> shasums

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            yeager-linux-amd64.tar.gz
            yeager-macos-amd64.tar.gz
            yeager-freebsd-amd64.tar.gz
            shasums
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: extract-version
        run: |
          printf "::set-output name=%s::%s\n" tag-name "${GITHUB_REF#refs/tags/}"

      - name: Update homebrew formula
        uses: mislav/bump-homebrew-formula-action@v1.12
        with:
          formula-name: yeager
          formula-path: Formula/yeager.rb
          homebrew-tap: chenen3/homebrew-yeager
          base-branch: master
          download-url: https://github.com/chenen3/yeager/releases/download/${{ steps.extract-version.outputs.tag-name }}/yeager-macos-amd64.tar.gz
          commit-message: |
            {{formulaName}} {{version}}

            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
