name: Release

on:
  release:
    types: [published]

jobs:
  binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - run: go version

      - name: Build
        id: build
        run: |
          ldflags="-X main.version=${{ github.ref_name }}"

          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="${ldflags}" -o yeager .
          tar -czf yeager-linux-amd64.tar.gz yeager README.md LICENSE
          shasum -a 256 yeager-linux-amd64.tar.gz >> shasums.txt

          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="${ldflags}" -o yeager .
          tar -czf yeager-macos-amd64.tar.gz yeager README.md LICENSE
          shasum -a 256 yeager-macos-amd64.tar.gz >> shasums.txt

          CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build -ldflags="${ldflags}" -o yeager .
          tar -czf yeager-freebsd-amd64.tar.gz yeager README.md LICENSE
          shasum -a 256 yeager-freebsd-amd64.tar.gz >> shasums.txt
          
          mac_bin_sha=$(shasum -a 256 yeager-macos-amd64.tar.gz |awk '{print $1}')
          echo "mac_bin_sha=$mac_bin_sha" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            yeager-linux-amd64.tar.gz
            yeager-macos-amd64.tar.gz
            yeager-freebsd-amd64.tar.gz
            shasums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump Homebrew formula
        uses: mislav/bump-homebrew-formula-action@v2
        with:
          formula-name: yeager
          formula-path: Formula/yeager.rb
          homebrew-tap: chenen3/homebrew-yeager
          base-branch: master
          download-url: https://github.com/chenen3/yeager/releases/download/${{ github.ref_name }}/yeager-macos-amd64.tar.gz
          # avoid downloading files that have just been uploaded, or they may fail
          download-sha256: ${{ steps.build.outputs.mac_bin_sha }}
          commit-message: |
            {{formulaName}} {{version}}

            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
